# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgStruct', '0005_departments_info_en_departments_info_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название отдела'),
        ),
    ]
