# Generated by Django 6.0 on 2026-01-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgStruct', '0006_alter_departments_name_alter_departments_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AddField(
            model_name='departments',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
