# Generated by Django 6.0 on 2025-12-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_alter_doctors_title_alter_doctors_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото педагогов'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото педагогов'),
        ),
    ]
