# Generated by Django 6.0 on 2026-01-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliensService', '0002_alter_compliensservice_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliensservice',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='compliensservice',
            name='title_en',
            field=models.CharField(max_length=512, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='compliensservice',
            name='title_kk',
            field=models.CharField(max_length=512, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='compliensservice',
            name='title_ru',
            field=models.CharField(max_length=512, null=True, verbose_name='Название'),
        ),
    ]
