# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scienceBlock', '0018_alter_science_options_alter_scienceachievments_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='science',
            name='addInfoTitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AlterField(
            model_name='science',
            name='addInfoTitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AlterField(
            model_name='science',
            name='addInfoTitle_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AlterField(
            model_name='science',
            name='addInfoTitle_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок подпунктов'),
        ),
        migrations.AlterField(
            model_name='scienceachievments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название презентации'),
        ),
        migrations.AlterField(
            model_name='scienceachievments',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название презентации'),
        ),
        migrations.AlterField(
            model_name='scienceachievments',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название презентации'),
        ),
        migrations.AlterField(
            model_name='scienceachievments',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название презентации'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='creation_title',
            field=models.CharField(max_length=255, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='creation_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='creation_title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='creation_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovet',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sciencesovetmeetings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetmeetings',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetmeetings',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetmeetings',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetplans',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetplans',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetplans',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetplans',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetregulation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetregulation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetregulation',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='sciencesovetregulation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
    ]
