# Generated by Django 6.0 on 2026-01-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео с YouTube (необязательно)', null=True, verbose_name='YouTube ссылка'),
        ),
    ]
