# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsBlog', '0005_alter_answer_options_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='IIN',
            field=models.CharField(max_length=255, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
