# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0014_rename_title_kz_ads_title_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название файла'),
        ),
    ]
