# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEK', '0007_alter_lek_creation_alter_lekmeetings_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lek',
            name='creation_title',
            field=models.CharField(max_length=255, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='creation_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='creation_title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='creation_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название приказа'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lek',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lekdocforms',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название формы документа'),
        ),
        migrations.AlterField(
            model_name='lekdocforms',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название формы документа'),
        ),
        migrations.AlterField(
            model_name='lekdocforms',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название формы документа'),
        ),
        migrations.AlterField(
            model_name='lekdocforms',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название формы документа'),
        ),
        migrations.AlterField(
            model_name='lekmeetings',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekmeetings',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekmeetings',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekmeetings',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekplans',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekplans',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekplans',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekplans',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekregulation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekregulation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekregulation',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='lekregulation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
    ]
