# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategicDevelopment', '0010_rename_name_kz_strategicdev_name_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategicdev',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='strategicdev',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='strategicdev',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='strategicdev',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название файла'),
        ),
    ]
