# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gobmp', '0006_alter_gobmp_additinaly_alter_gobmp_additinaly_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobmp',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gobmp',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gobmp',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gobmp',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
