# Generated by Django 6.0 on 2026-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCouncilDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('document', models.FileField(blank=True, upload_to='academicCouncil/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы (Скачивание)',
            },
        ),
        migrations.CreateModel(
            name='AcademicCouncilInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='AcademicCouncilMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('title_kk', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название документа')),
                ('document', models.FileField(blank=True, upload_to='academicCouncil/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Заседание',
                'verbose_name_plural': 'Заседания (Просмотр)',
            },
        ),
    ]
