# Generated by Django 6.0 on 2026-02-02 07:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('file', models.FileField(upload_to='books/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='digital_lib_search__bc8c41_gin')],
            },
        ),
        # ТРИГГЕР ДЛЯ ОБНОВЛЕНИЯ search_vector
        migrations.RunSQL(
            sql='''
                CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
                ON digital_library_book FOR EACH ROW EXECUTE PROCEDURE
                tsvector_update_trigger(search_vector, 'pg_catalog.simple', title, description);
            ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS search_vector_update ON digital_library_book;
            '''
        ),
    ]