# Generated by Django 6.0 on 2026-02-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.RunSQL(
            sql='''
                DROP TRIGGER IF EXISTS search_vector_update ON digital_library_book;
                CREATE TRIGGER search_vector_update BEFORE INSERT OR UPDATE
                ON digital_library_book FOR EACH ROW EXECUTE PROCEDURE
                tsvector_update_trigger(search_vector, 'pg_catalog.simple', title_ru, title_en, title_kk, author_ru, author_en, author_kk, description_ru, description_en, description_kk);
            ''',
            reverse_sql='''
                DROP TRIGGER IF EXISTS search_vector_update ON digital_library_book;
            '''
        ),
    ]
