# Generated by Django 6.0 on 2026-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_library', '0002_book_author_en_book_author_kk_book_author_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/books/covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='media/books/files/', verbose_name='Книга (файл)'),
        ),
    ]
