"""
Django settings for minZdrav project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = 'logRegisPages.CustomUser'

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1ya8j+33+d*5@vbvbujj()6kg^zg^j0q&qc^(=w!5ka3l%*4b)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'modeltranslation',
    'django_recaptcha',  # Убедитесь, что 'captcha' здесь
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news',
    'static_pages',
    'info_page',
    'contact_pages',
    'history_legends',
    'ceoInfo',
    'vacancies',
    'viewSovet',
    'logRegisPages',
    'orgStruct',
    'ProvActs',
    'workersInfo',
    'antiCorruptions',
    'medServices',
    'aboutPage',
    'reviewsBlog',
    'advertisement',
    'appeal',
    'ceoblog',
    'people',
    'accreditation',
    'strategicDevelopment',
    'ethica',
    'mediagallery',
    'strategic_partners',
    'scienceBlock',
    'booking',
    'gobmp',
    'laborProtection',
    'compliensService',
    'LEK',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

###CSRF_COOKIE_DOMAIN = '.burabay-mzrk.kz'
CSRF_COOKIE_DOMAIN = 'burabay-mzrk.kz'
CSRF_TRUSTED_ORIGINS = ['https://burabay-mzrk.kz', 'https://www.burabay-mzrk.kz']

ROOT_URLCONF = 'minZdrav.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR , 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'minZdrav.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'burabay_mzrk',      # название базы, которую ты создал
        'USER': 'userdb',     # стандартный пользователь
        'PASSWORD': 'DB_pass8811',  # пароль, который ты вводил при установке
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

X_FRAME_OPTIONS = "SAMEORIGIN"

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Asia/Almaty'
USE_I18N = True
USE_L10N = True
USE_TZ = True

gettext = lambda s: s
LANGUAGES = (
    ('ru', gettext('Russian')),
    ('kk', gettext('Kazakh')),
    ('en', gettext('English')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static')
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'marlan-esilbaev@mail.ru'
EMAIL_HOST_PASSWORD = 'AkFxcunrb1Wyw256RtF6'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGOUT_URL = 'login'
LOGIN_URL = 'login'

# Настройки reCAPTCHA
RECAPTCHA_PUBLIC_KEY = '6LfG8gIqAAAAAOh1cHtY6b2dg2K_IDjP6AZpKbLU'
RECAPTCHA_PRIVATE_KEY = '6LfG8gIqAAAAABGjZCloN2O9dpSBgkQrTDGM_q94'
RECAPTCHA_USE_SSL = True
