# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0011_rename_post_kz_workersinfo_post_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workersinfo',
            name='work_exp',
            field=models.CharField(max_length=255, verbose_name='Стаж'),
        ),
    ]
