# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_pages', '0013_remove_index_page_bannercontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinfo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='openinfo',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='openinfo',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='openinfo',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
