# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0015_alter_managers_reception_alter_managers_reception_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='infoaccessfaces',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='email',
            field=models.CharField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='managers',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
    ]
