# Generated by Django 6.0 on 2026-01-05 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoblog', '0010_alter_postattachment_file_alter_postattachment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postceo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Например: https://youtu.be/VIDEO_ID или https://www.youtube.com/watch?v=VIDEO_ID', null=True, verbose_name='YouTube ссылка'),
        ),
        migrations.AlterField(
            model_name='postattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ceoblog.postceo', verbose_name='Сообщение'),
        ),
    ]
