# Generated by Django 6.0 on 2026-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoblog', '0011_postceo_youtube_url_alter_postattachment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postceo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Ссылка на видео с YouTube (необязательно)', null=True, verbose_name='YouTube ссылка'),
        ),
    ]
