# Generated by Django 6.0 on 2026-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Название отдела')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название отдела')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название отдела')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название отдела')),
                ('info', models.TextField(verbose_name='Информация об отделе')),
                ('info_ru', models.TextField(null=True, verbose_name='Информация об отделе')),
                ('info_kk', models.TextField(null=True, verbose_name='Информация об отделе')),
                ('info_en', models.TextField(null=True, verbose_name='Информация об отделе')),
                ('head_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('head_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('head_name_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('head_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО руководителя')),
                ('head_photo', models.ImageField(blank=True, null=True, upload_to='departments_heads/', verbose_name='Фото руководителя')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgStruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs/', verbose_name='Файл с изображением организационной структуры')),
                ('file_ru', models.FileField(null=True, upload_to='docs/', verbose_name='Файл с изображением организационной структуры')),
                ('file_kk', models.FileField(null=True, upload_to='docs/', verbose_name='Файл с изображением организационной структуры')),
                ('file_en', models.FileField(null=True, upload_to='docs/', verbose_name='Файл с изображением организационной структуры')),
            ],
            options={
                'verbose_name': 'Схема',
                'verbose_name_plural': 'Схемы отделов',
            },
        ),
    ]
