# Generated by Django 5.0.2 on 2025-11-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0022_rename_awards_kz_ceodatas_awards_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceodatas',
            name='dateOfBirth',
            field=models.CharField(max_length=255, verbose_name='Дата рождания'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='dateOfBirth_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Дата рождания'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='dateOfBirth_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Дата рождания'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='dateOfBirth_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Дата рождания'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя руководителя'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='post',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='post_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='post_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='ceodatas',
            name='post_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
