# Generated by Django 6.0 on 2026-01-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0023_alter_ceodatas_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ceodatas',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Информация о руководителе'},
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
