# Generated by Django 6.0 on 2026-07-03 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOKGeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Заголовок комплекса (напр. LOK Astana)')),
                ('hero_title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок комплекса (напр. LOK Astana)')),
                ('hero_title_kk', models.CharField(max_length=255, null=True, verbose_name='Заголовок комплекса (напр. LOK Astana)')),
                ('hero_title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок комплекса (напр. LOK Astana)')),
                ('hero_bg', models.ImageField(blank=True, null=True, upload_to='lok_media/', verbose_name='Фон главного экрана')),
                ('value_title', models.CharField(default='Ценность проекта', max_length=255, verbose_name='Заголовок: Ценность')),
                ('value_title_ru', models.CharField(default='Ценность проекта', max_length=255, null=True, verbose_name='Заголовок: Ценность')),
                ('value_title_kk', models.CharField(default='Ценность проекта', max_length=255, null=True, verbose_name='Заголовок: Ценность')),
                ('value_title_en', models.CharField(default='Ценность проекта', max_length=255, null=True, verbose_name='Заголовок: Ценность')),
                ('value_text', models.TextField(verbose_name='Текст: Ценность')),
                ('value_text_ru', models.TextField(null=True, verbose_name='Текст: Ценность')),
                ('value_text_kk', models.TextField(null=True, verbose_name='Текст: Ценность')),
                ('value_text_en', models.TextField(null=True, verbose_name='Текст: Ценность')),
                ('features_title', models.CharField(default='Особенности', max_length=255, verbose_name='Заголовок: Особенности')),
                ('features_title_ru', models.CharField(default='Особенности', max_length=255, null=True, verbose_name='Заголовок: Особенности')),
                ('features_title_kk', models.CharField(default='Особенности', max_length=255, null=True, verbose_name='Заголовок: Особенности')),
                ('features_title_en', models.CharField(default='Особенности', max_length=255, null=True, verbose_name='Заголовок: Особенности')),
                ('features_text', models.TextField(verbose_name='Текст: Особенности')),
                ('features_text_ru', models.TextField(null=True, verbose_name='Текст: Особенности')),
                ('features_text_kk', models.TextField(null=True, verbose_name='Текст: Особенности')),
                ('features_text_en', models.TextField(null=True, verbose_name='Текст: Особенности')),
                ('contacts_title', models.CharField(default='Наши контакты', max_length=255, verbose_name='Заголовок контактов')),
                ('contacts_title_ru', models.CharField(default='Наши контакты', max_length=255, null=True, verbose_name='Заголовок контактов')),
                ('contacts_title_kk', models.CharField(default='Наши контакты', max_length=255, null=True, verbose_name='Заголовок контактов')),
                ('contacts_title_en', models.CharField(default='Наши контакты', max_length=255, null=True, verbose_name='Заголовок контактов')),
                ('contacts_text', models.TextField(verbose_name='Текст контактов (адрес, телефон)')),
                ('contacts_text_ru', models.TextField(null=True, verbose_name='Текст контактов (адрес, телефон)')),
                ('contacts_text_kk', models.TextField(null=True, verbose_name='Текст контактов (адрес, телефон)')),
                ('contacts_text_en', models.TextField(null=True, verbose_name='Текст контактов (адрес, телефон)')),
            ],
            options={
                'verbose_name': 'Главная страница ЛОК',
                'verbose_name_plural': 'Главная страница ЛОК',
            },
        ),
        migrations.CreateModel(
            name='LOKRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название номера (напр. Люкс)')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название номера (напр. Люкс)')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название номера (напр. Люкс)')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название номера (напр. Люкс)')),
                ('short_desc', models.TextField(verbose_name='Краткое описание (для карточки)')),
                ('short_desc_ru', models.TextField(null=True, verbose_name='Краткое описание (для карточки)')),
                ('short_desc_kk', models.TextField(null=True, verbose_name='Краткое описание (для карточки)')),
                ('short_desc_en', models.TextField(null=True, verbose_name='Краткое описание (для карточки)')),
                ('full_desc', models.TextField(verbose_name='Полное описание (для окна)')),
                ('full_desc_ru', models.TextField(null=True, verbose_name='Полное описание (для окна)')),
                ('full_desc_kk', models.TextField(null=True, verbose_name='Полное описание (для окна)')),
                ('full_desc_en', models.TextField(null=True, verbose_name='Полное описание (для окна)')),
                ('cover_image', models.ImageField(upload_to='lok_rooms/', verbose_name='Главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номерной фонд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LOKService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название услуги')),
                ('name_kk', models.CharField(max_length=255, null=True, verbose_name='Название услуги')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_kk', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='lok_services/', verbose_name='Иллюстрация')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LOKRoomGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lok_rooms/gallery/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='LOKAstanaInfo.lokroom')),
            ],
        ),
    ]
